inherit_from: ../.rubocop.yml

# Baseline code complexity metrics for the bin/ subdirectory:

Metrics/AbcSize:
  Max: 49

Metrics/CyclomaticComplexity:
  Max: 23

Metrics/MethodLength:
  Max: 50

Metrics/ParameterLists:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 24
