# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: ems.proto for package 'IOSXRExtensibleManagabilityService'

require 'grpc'
require_relative 'ems'

module IOSXRExtensibleManagabilityService
  module GRPCConfigOper

    # TODO: add proto service documentation here
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'IOSXRExtensibleManagabilityService.gRPCConfigOper'

      rpc :GetConfig, ConfigGetArgs, stream(ConfigGetReply)
      rpc :MergeConfig, ConfigArgs, ConfigReply
      rpc :DeleteConfig, ConfigArgs, ConfigReply
      rpc :ReplaceConfig, ConfigArgs, ConfigReply
      rpc :CliConfig, CliConfigArgs, CliConfigReply
      rpc :CommitReplace, CommitReplaceArgs, CommitReplaceReply
      rpc :CommitConfig, CommitArgs, CommitReply
      rpc :ConfigDiscardChanges, DiscardChangesArgs, DiscardChangesReply
      rpc :GetOper, GetOperArgs, stream(GetOperReply)
    end

    Stub = Service.rpc_stub_class
  end
  module GRPCExec

    # TODO: add proto service documentation here
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'IOSXRExtensibleManagabilityService.gRPCExec'

      rpc :ShowCmdTextOutput, ShowCmdArgs, stream(ShowCmdTextReply)
      rpc :ShowCmdJSONOutput, ShowCmdArgs, stream(ShowCmdJSONReply)
    end

    Stub = Service.rpc_stub_class
  end
end
