#!/bin/bash
#
# Runs at the end of 'git flow release finish x.y.z'
#
# Positional arguments:
# $1    The version (including the version prefix)
# $2    The origin remote
# $3    The full branch name (including the release prefix)

VERSION=$1
ORIGIN=$2
BRANCH=$3

echo

STRIP_VERSION=$(echo $VERSION | tr -c -d '0-9.')

ROOT=$(git rev-parse --show-toplevel)

# Add new 'Unreleased' section header to the CHANGELOG
sed -i "/^=========$/ a\
\\\n## [Unreleased]\n
" $ROOT/CHANGELOG.md

echo "Updated CHANGELOG.md for develop branch"

# Bump the minor version number
BUGFIX_NUM=$(($(echo $STRIP_VERSION | cut -d. -f 3)+1))
NEW_VERSION="$(echo $STRIP_VERSION | cut -d. -f 1-2).$BUGFIX_NUM-dev"

echo "New development version will be $NEW_VERSION"
sed -i -e "s/VERSION = .*/VERSION = '$NEW_VERSION'/" $ROOT/lib/cisco_node_utils/version.rb

echo "Updated version.rb for develop branch"

git commit -a -m "Post-release fixup"

echo

exit 0
