#!/bin/bash
#
# Script run at the end of 'git flow release start x.y.z'
#
# Positional arguments:
# $1    The version (including the version prefix)
# $2    The origin remote
# $3    The full branch name (including the 'release' prefix)
#

VERSION=$1
STRIP_VERSION=$(echo $VERSION | tr -c -d '0-9.')

ROOT=$(git rev-parse --show-toplevel)

# Get the last release version from the CHANGELOG
LAST_VERSION=$(egrep -m 2 '## \[.*]' $ROOT/CHANGELOG.md | grep -v 'Unreleased' | cut -d ' ' -f 2 | tr -d '[]')

echo "Detected previous release version as '$LAST_VERSION'"

# Automatically update the CHANGELOG to mark the new release.
sed -i -e "s/^## \[Unreleased\]$/## [$VERSION] - $(date +%Y-%m-%d)/" $ROOT/CHANGELOG.md

# Automatically add diff link to the CHANGELOG too.
sed -i "/master...develop/ a\
[$VERSION]: https://github.com/cisco/cisco-network-node-utils/compare/$LAST_VERSION...$VERSION
" $ROOT/CHANGELOG.md

echo "Updated CHANGELOG.md for release $VERSION"

# Automatically update the gem version as well
sed -i -e "s/VERSION =.*/VERSION = '$STRIP_VERSION'/" $ROOT/lib/cisco_node_utils/version.rb

echo "Updated version.rb for release $STRIP_VERSION"
