# Kwalify schema for cmd_ref YAML files

type: map
mapping:
  # List of cases to specifically exclude
  _exclude: &exclude
    type: seq
    sequence:
      - type: str
        enum: &filters # Things we can filter by
          # Platform classes
          - 'ios_xr'
          - 'nexus'
          # Product IDs
          - 'C3064'
          - 'C3132'
          - 'C3172'
          - 'N3k'
          - 'N5k'
          - 'N6k'
          - 'N7k'
          - 'N9k'
          - 'N9k-F'

  =: &base # default rule - apply to all properties
    type: map
    mapping:
      _exclude: *exclude
      # Platform and product filters
      ios_xr: *base
      nexus: *base
      C3064: *base
      C3132: *base
      C3172: *base
      N3k: *base
      N5k: *base
      N6k: *base
      N7k: *base
      N9k: *base
      N9k-F: *base
      # 'else' case if not matching any filter above
      else: *base
      # Generally applicable attributes
      data_format: &data_format
        type: str
        enum: [cli, nxapi_structured]
      context: &context
        type: seq
        sequence:
          - type: str
      value:
        type: str
      default_only:
        type: any
      # Getter-specific attributes
      auto_default:
        type: bool
      default_value:
        type: any
      get_command:
        type: str
      get_data_format: *data_format
      get_context: *context
      get_value:
        type: any
      kind:
        type: str
        enum: [boolean, int, string, symbol]
      multiple:
        type: bool
      # Setter-specific attributes
      set_data_format: *data_format
      set_context: *context
      set_value:
        type: str
